/* ============================================================
   台股全景資料庫 — Top 300 公司
   欄位：code(股號), name, sector, subSector, group, rank(市值約略排名),
         business(主營業務), products(產品/服務), founded(成立), market
   注意：rank 為大致順序而非即時排名；股價/本益比/即時資料請走外部連結。
   ============================================================ */
window.COMPANIES = [
  /* ========= 半導體 ========= */
  {code:"2330",name:"台積電",sector:"半導體",subSector:"晶圓代工",group:"獨立",rank:1,
   business:"全球最大專業積體電路製造服務（晶圓代工）公司，提供 2nm/3nm/5nm/7nm 先進製程及成熟製程服務",
   products:["3nm/5nm/7nm 先進製程","成熟製程","CoWoS/InFO 先進封裝","車用半導體"],founded:1987},
  {code:"2454",name:"聯發科",sector:"半導體",subSector:"IC設計",group:"獨立",rank:3,
   business:"全球第四大 IC 設計公司，主攻手機 SoC、Wi-Fi、ASIC、AI 加速器晶片",
   products:["天璣系列手機 SoC","Wi-Fi/藍牙晶片","ASIC 客製化","電視 SoC"],founded:1997},
  {code:"2303",name:"聯電",sector:"半導體",subSector:"晶圓代工",group:"聯電集團",rank:14,
   business:"全球第三大晶圓代工廠，專注 28nm/22nm 成熟與特殊製程",
   products:["28nm/22nm 邏輯製程","RF/嵌入式記憶體","車用 IC 製程"],founded:1980},
  {code:"3711",name:"日月光投控",sector:"半導體",subSector:"封裝測試",group:"日月光集團",rank:11,
   business:"全球最大半導體封裝測試廠，提供先進封裝、測試與材料服務",
   products:["FCBGA/FCCSP","SiP 系統級封裝","CoWoS 後段封裝","測試服務"],founded:2018},
  {code:"6488",name:"環球晶",sector:"半導體",subSector:"矽晶圓",group:"中美晶集團",rank:38,
   business:"全球第三大矽晶圓供應商，產品涵蓋 4-12 吋",
   products:["12吋拋光晶圓","磊晶晶圓","SOI 晶圓"],founded:2011},
  {code:"5347",name:"世界先進",sector:"半導體",subSector:"晶圓代工",group:"台積電集團",rank:55,
   business:"專注 8 吋晶圓代工，主力 PMIC、Driver IC、特殊製程",
   products:["8吋成熟製程","電源管理 IC","Display Driver"],founded:1994},
  {code:"3034",name:"聯詠",sector:"半導體",subSector:"IC設計",group:"聯電集團",rank:19,
   business:"全球大型 Display Driver IC 設計廠，主攻面板驅動 IC、SoC",
   products:["LCD/OLED Driver IC","TCON","TV/監控 SoC"],founded:1997},
  {code:"2379",name:"瑞昱",sector:"半導體",subSector:"IC設計",group:"獨立",rank:25,
   business:"網通與多媒體 IC 設計，主攻 PC 網卡、Switch、Wi-Fi",
   products:["乙太網路晶片","Wi-Fi/藍牙","音效晶片","電視/Switch SoC"],founded:1987},
  {code:"3035",name:"智原",sector:"半導體",subSector:"IC設計服務",group:"聯電集團",rank:120,
   business:"IC 設計服務（ASIC/IP）廠商，提供 SoC turnkey 服務",
   products:["ASIC 設計","矽智財授權","SoC turnkey"],founded:1993},
  {code:"3443",name:"創意",sector:"半導體",subSector:"IC設計服務",group:"台積電集團",rank:42,
   business:"台積電轉投資 ASIC 設計服務廠，AI/HPC ASIC 主要供應商之一",
   products:["AI ASIC","HPC ASIC","網通 ASIC","封測整合"],founded:2003},
  {code:"5274",name:"信驊",sector:"半導體",subSector:"IC設計",group:"獨立",rank:65,
   business:"全球伺服器遠端管理 BMC 晶片龍頭",
   products:["BMC 晶片","SoC for server"],founded:2004},
  {code:"3105",name:"穩懋",sector:"半導體",subSector:"化合物半導體",group:"獨立",rank:78,
   business:"全球最大砷化鎵代工廠，主攻 RF PA、VCSEL",
   products:["GaAs RF","VCSEL","BiHEMT"],founded:1999},
  {code:"3661",name:"世芯-KY",sector:"半導體",subSector:"IC設計服務",group:"獨立",rank:35,
   business:"ASIC 設計服務廠，專注 AI、HPC、網通客戶",
   products:["AI ASIC","HPC ASIC","網通晶片"],founded:2003,market:"KY"},
  {code:"6770",name:"力積電",sector:"半導體",subSector:"晶圓代工",group:"獨立",rank:90,
   business:"DRAM 與 8/12 吋晶圓代工，包含記憶體與邏輯製程",
   products:["DRAM","邏輯代工","面板驅動 IC"],founded:1994},
  {code:"8081",name:"致新",sector:"半導體",subSector:"IC設計",group:"獨立",rank:160,
   business:"電源管理 IC 設計，類比 IC 主要供應商",
   products:["PMIC","DC-DC","LED Driver"]},
  {code:"3014",name:"聯陽",sector:"半導體",subSector:"IC設計",group:"聯電集團",rank:170,
   business:"PC 周邊 IC 設計，KB controller、Touch IC",
   products:["KBC","Touch IC","HID"]},
  {code:"5269",name:"祥碩",sector:"半導體",subSector:"IC設計",group:"華碩集團",rank:80,
   business:"USB / SATA / PCIe 控制晶片，AMD 主要協作夥伴",
   products:["USB 4 控制晶片","SATA/PCIe","Chipset 晶片"]},
  {code:"6202",name:"盛群",sector:"半導體",subSector:"IC設計",group:"獨立",rank:230,
   business:"MCU 微控制器主力廠，家電與消費電子應用",
   products:["8/16/32-bit MCU","Touch IC"]},
  {code:"3529",name:"力旺",sector:"半導體",subSector:"矽智財",group:"獨立",rank:60,
   business:"全球嵌入式非揮發性記憶體（eNVM）矽智財龍頭",
   products:["eNVM IP","RRAM/PUF IP"]},
  {code:"4961",name:"天鈺",sector:"半導體",subSector:"IC設計",group:"鴻海集團",rank:140,
   business:"Display Driver IC、TCON、PMIC",
   products:["Driver IC","TCON","PMIC"]},
  {code:"6643",name:"M31",sector:"半導體",subSector:"矽智財",group:"獨立",rank:130,
   business:"高速介面矽智財授權，USB/PCIe/MIPI/HDMI",
   products:["USB IP","PCIe IP","MIPI IP"]},
  {code:"6515",name:"穎崴",sector:"半導體",subSector:"測試介面",group:"獨立",rank:100,
   business:"半導體測試介面 Probe Card、Test Socket 領導廠",
   products:["Probe Card","Test Socket"]},
  {code:"6271",name:"同欣電",sector:"半導體",subSector:"封測",group:"獨立",rank:175,
   business:"CMOS 影像感測器封裝、混合電路封測",
   products:["CIS 封裝","混合 IC 封測"]},
  {code:"2449",name:"京元電",sector:"半導體",subSector:"測試",group:"獨立",rank:75,
   business:"全球大型 IC 測試代工廠，5G/HPC 主要測試夥伴",
   products:["邏輯 IC 測試","RF 測試","SoC 測試"]},
  {code:"3413",name:"京鼎",sector:"半導體",subSector:"設備",group:"鴻海集團",rank:115,
   business:"半導體製程設備模組與零組件，AMAT 重要供應商",
   products:["半導體設備模組","模組零組件"]},
  {code:"6446",name:"藥華藥",sector:"生技醫療",subSector:"製藥",group:"獨立",rank:155,
   business:"專注罕見血液疾病新藥開發（Ropeg 干擾素）",
   products:["Besremi (PV)","新藥研發"]},
  {code:"4968",name:"立積",sector:"半導體",subSector:"IC設計",group:"獨立",rank:185,
   business:"Wi-Fi 射頻前端 IC 設計龍頭",
   products:["Wi-Fi 6/7 RF FEM","BT FEM"]},
  {code:"8261",name:"富鼎",sector:"半導體",subSector:"功率元件",group:"獨立",rank:240,
   business:"MOSFET 功率元件設計",
   products:["MOSFET","Power IC"]},
  {code:"3530",name:"晶相光",sector:"半導體",subSector:"IC設計",group:"獨立",rank:200,
   business:"CMOS 影像感測器設計",
   products:["CIS","車用影像感測"]},
  {code:"3653",name:"健策",sector:"半導體",subSector:"散熱基板",group:"獨立",rank:88,
   business:"半導體散熱基板（CPC）、銅基板，AI 伺服器供應鏈",
   products:["散熱基板","銅夾","CCL"]},

  /* ========= 電腦及週邊 ========= */
  {code:"2317",name:"鴻海",sector:"電腦及週邊",subSector:"電子組裝",group:"鴻海集團",rank:2,
   business:"全球最大 EMS 代工廠，蘋果 iPhone 主要組裝廠，AI 伺服器代工龍頭",
   products:["iPhone 組裝","AI 伺服器","電動車 MIH 平台","半導體封測"],founded:1974},
  {code:"2382",name:"廣達",sector:"電腦及週邊",subSector:"NB/伺服器",group:"獨立",rank:9,
   business:"全球大型 NB 代工廠之一，AI 伺服器代工主要供應商",
   products:["NB ODM","AI 伺服器","資料中心硬體"],founded:1988},
  {code:"2357",name:"華碩",sector:"電腦及週邊",subSector:"NB品牌",group:"華碩集團",rank:18,
   business:"NB 與電競周邊品牌領導廠",
   products:["NB / ROG 電競","主機板/顯卡","伺服器","ZenFone"],founded:1989},
  {code:"3231",name:"緯創",sector:"電腦及週邊",subSector:"NB/伺服器",group:"緯創集團",rank:33,
   business:"NB 與伺服器代工廠，緯穎母公司",
   products:["NB ODM","AI 伺服器","顯示器","醫療 IT"],founded:2001},
  {code:"2353",name:"宏碁",sector:"電腦及週邊",subSector:"NB品牌",group:"宏碁集團",rank:120,
   business:"NB 全球品牌廠，跨足電競、永續、商用 IT",
   products:["NB / Predator","顯示器","電競周邊"],founded:1976},
  {code:"2356",name:"英業達",sector:"電腦及週邊",subSector:"NB/伺服器",group:"獨立",rank:50,
   business:"NB、伺服器、智慧裝置代工",
   products:["NB ODM","伺服器","AI 伺服器"]},
  {code:"6669",name:"緯穎",sector:"電腦及週邊",subSector:"雲端伺服器",group:"緯創集團",rank:22,
   business:"超大規模資料中心客製化伺服器（ODM Direct）龍頭",
   products:["雲端伺服器","儲存設備","網通設備"],founded:2012},
  {code:"4938",name:"和碩",sector:"電腦及週邊",subSector:"電子組裝",group:"華碩集團",rank:32,
   business:"原華碩代工部門 spin-off，iPhone/iPad 主要組裝廠之一",
   products:["iPhone/iPad 組裝","NB","Switch"],founded:2008},
  {code:"2376",name:"技嘉",sector:"電腦及週邊",subSector:"主機板/伺服器",group:"獨立",rank:48,
   business:"主機板、顯卡、AI 伺服器領導廠",
   products:["主機板","顯卡","AI 伺服器","電競周邊"],founded:1986},
  {code:"2377",name:"微星",sector:"電腦及週邊",subSector:"主機板/AI",group:"獨立",rank:53,
   business:"主機板、顯卡、電競 NB、AI 伺服器",
   products:["主機板","顯卡","電競 NB","AI 伺服器"],founded:1986},
  {code:"2474",name:"可成",sector:"電腦及週邊",subSector:"金屬機殼",group:"可成集團",rank:62,
   business:"NB/手機金屬機殼龍頭，醫療、車用拓展中",
   products:["NB 機殼","Server 機殼","醫療元件"],founded:1984},
  {code:"3017",name:"奇鋐",sector:"電腦及週邊",subSector:"散熱",group:"獨立",rank:36,
   business:"AI 伺服器散熱模組龍頭，水冷方案",
   products:["散熱模組","液冷散熱","風扇"],founded:1989},
  {code:"2360",name:"致茂",sector:"電腦及週邊",subSector:"自動測試設備",group:"獨立",rank:71,
   business:"自動測試設備（ATE）龍頭，半導體/電池/電動車測試",
   products:["半導體 ATE","電池/電動車測試","面板測試"],founded:1984},
  {code:"2451",name:"創見",sector:"電腦及週邊",subSector:"記憶體模組",group:"獨立",rank:165,
   business:"記憶體模組、SSD 模組品牌廠",
   products:["DRAM 模組","SSD","儲存方案"]},
  {code:"3380",name:"明泰",sector:"電腦及週邊",subSector:"網通設備",group:"獨立",rank:215,
   business:"網通設備代工，企業級交換器、AP",
   products:["交換器","Wi-Fi AP","路由器"]},
  {code:"6230",name:"超眾",sector:"電腦及週邊",subSector:"散熱",group:"鴻海集團",rank:140,
   business:"散熱模組製造，鴻海集團子公司",
   products:["散熱模組","均熱片","風扇"]},
  {code:"8210",name:"勤誠",sector:"電腦及週邊",subSector:"伺服器機殼",group:"獨立",rank:135,
   business:"伺服器機殼領導廠，AI server casing",
   products:["伺服器機殼","資料中心機箱"]},
  {code:"3443",name:"創意",sector:"半導體",subSector:"IC設計服務",group:"台積電集團",rank:42,
   business:"重複條目（已列），略過"},
  {code:"3260",name:"威剛",sector:"電腦及週邊",subSector:"記憶體模組",group:"獨立",rank:150,
   business:"DRAM 模組、SSD、工控記憶體領導廠",
   products:["DRAM 模組","SSD","工控記憶體"]},

  /* ========= 電子零組件 ========= */
  {code:"2308",name:"台達電",sector:"電子零組件",subSector:"電源/工業電源",group:"台達集團",rank:7,
   business:"全球電源管理、工業自動化、電動車電力電子龍頭",
   products:["伺服器電源","工業自動化","EV 動力","樓宇自動化"],founded:1971},
  {code:"2327",name:"國巨",sector:"電子零組件",subSector:"被動元件",group:"國巨集團",rank:24,
   business:"全球前三大被動元件廠，整合 KEMET、Pulse",
   products:["MLCC","電阻","電感","Tantalum 電容"],founded:1977},
  {code:"2301",name:"光寶科",sector:"電子零組件",subSector:"電源/光電",group:"光寶集團",rank:46,
   business:"電源供應器、雲端電源、汽車電子",
   products:["雲端電源","車用電子","LED"]},
  {code:"2354",name:"鴻準",sector:"電子零組件",subSector:"金屬機構件",group:"鴻海集團",rank:80,
   business:"鴻海集團機構件廠，散熱、機殼、精密金屬",
   products:["NB/手機機殼","散熱模組","電動車零組件"]},
  {code:"2392",name:"正崴",sector:"電子零組件",subSector:"連接器",group:"鴻海集團",rank:175,
   business:"連接器、線材、車用電子",
   products:["連接器","車用線束","電池"]},
  {code:"6213",name:"聯茂",sector:"電子零組件",subSector:"銅箔基板",group:"獨立",rank:105,
   business:"高階銅箔基板（CCL）廠，AI server PCB 主要供應",
   products:["高頻 CCL","HDI 基板"]},
  {code:"8046",name:"南電",sector:"電子零組件",subSector:"IC載板",group:"台塑集團",rank:43,
   business:"全球大型 ABF 載板供應商，AI HPC 與 CPU 主力",
   products:["ABF 載板","BT 載板"]},
  {code:"6121",name:"新普",sector:"電子零組件",subSector:"鋰電池模組",group:"獨立",rank:170,
   business:"NB/手機鋰電池模組龍頭",
   products:["NB 電池模組","電動工具電池","儲能"]},
  {code:"2059",name:"川湖",sector:"電子零組件",subSector:"伺服器滑軌",group:"獨立",rank:95,
   business:"伺服器滑軌與機構件全球龍頭",
   products:["server 滑軌","資料中心機構"]},
  {code:"3037",name:"欣興",sector:"電子零組件",subSector:"PCB/載板",group:"聯電集團",rank:30,
   business:"全球前段大 PCB 與 IC 載板廠，AI 載板主力",
   products:["ABF 載板","HDI PCB","軟硬板"]},
  {code:"6669",name:"緯穎",sector:"電腦及週邊",subSector:"雲端伺服器",group:"緯創集團",rank:22,
   business:"重複"},
  {code:"3044",name:"健鼎",sector:"電子零組件",subSector:"PCB",group:"獨立",rank:108,
   business:"電腦/通訊用 PCB，伺服器與車用比重提升",
   products:["伺服器 PCB","車用 PCB","HDI"]},
  {code:"6285",name:"啟碁",sector:"通信網路",subSector:"網通",group:"仁寶集團",rank:120,
   business:"無線通訊產品，網通、車用、衛星通訊"},
  {code:"3023",name:"信邦",sector:"電子零組件",subSector:"連接器/線材",group:"獨立",rank:160,
   business:"連接線、連接器，工控/汽車/醫療客製化"},

  /* ========= 光電 ========= */
  {code:"3008",name:"大立光",sector:"光電",subSector:"光學鏡頭",group:"獨立",rank:21,
   business:"全球高階手機鏡頭龍頭",
   products:["手機鏡頭","車用鏡頭","AR/VR 鏡頭"],founded:1987},
  {code:"3406",name:"玉晶光",sector:"光電",subSector:"光學鏡頭",group:"獨立",rank:118,
   business:"高階光學鏡頭，蘋果重要供應商",
   products:["手機鏡頭","AR/VR 鏡頭"]},
  {code:"3481",name:"群創",sector:"光電",subSector:"面板",group:"鴻海集團",rank:85,
   business:"中大尺寸液晶面板廠，車用面板比重提升",
   products:["LCD 面板","車用顯示器","Mini LED"]},
  {code:"2409",name:"友達",sector:"光電",subSector:"面板",group:"獨立",rank:70,
   business:"中大尺寸面板廠，跨足智慧醫療、Micro LED",
   products:["LCD 面板","車用面板","Micro LED"]},
  {code:"6116",name:"彩晶",sector:"光電",subSector:"面板",group:"獨立",rank:160,
   business:"中小尺寸面板廠"},
  {code:"3293",name:"鈊象",sector:"資訊服務",subSector:"遊戲",group:"獨立",rank:99,
   business:"線上博弈與電子遊戲開發商"},
  {code:"5371",name:"中光電",sector:"光電",subSector:"投影/光源",group:"中光電集團",rank:170,
   business:"投影機光學引擎、車用 HUD、節能照明"},
  {code:"3105",name:"穩懋",sector:"半導體",subSector:"化合物半導體",group:"獨立",rank:78,business:"重複"},

  /* ========= 通信網路 ========= */
  {code:"2412",name:"中華電",sector:"通信網路",subSector:"電信",group:"獨立",rank:8,
   business:"台灣最大電信公司，行動通信、固網、寬頻、雲端",
   products:["行動通信","光纖寬頻","資料中心","IDC"]},
  {code:"3045",name:"台灣大",sector:"通信網路",subSector:"電信",group:"富邦集團",rank:40,
   business:"電信、有線電視、富邦集團通信旗艦",
   products:["行動通信","myVideo","momo（持股）"]},
  {code:"4904",name:"遠傳",sector:"通信網路",subSector:"電信",group:"遠東集團",rank:54,
   business:"遠東集團電信業旗艦，與亞太電合併",
   products:["行動通信","企業數位服務","友訊"]},
  {code:"2345",name:"智邦",sector:"通信網路",subSector:"網通設備",group:"獨立",rank:34,
   business:"資料中心 Switch 龍頭代工廠，AI Networking 受惠者",
   products:["Data Center Switch","邊緣交換器","網通 ODM"]},
  {code:"5388",name:"中磊",sector:"通信網路",subSector:"網通設備",group:"獨立",rank:130,
   business:"電信寬頻終端設備代工"},

  /* ========= 電子通路 ========= */
  {code:"3702",name:"大聯大",sector:"電子通路",subSector:"半導體通路",group:"獨立",rank:65,
   business:"亞太最大半導體零組件通路商",
   products:["半導體分銷","供應鏈服務"]},
  {code:"3036",name:"文曄",sector:"電子通路",subSector:"半導體通路",group:"獨立",rank:60,
   business:"亞洲大型 IC 通路商，整併富昌電子全球擴張",
   products:["IC 分銷","電源/類比 IC 通路"]},

  /* ========= 資訊服務 ========= */
  {code:"8044",name:"網家",sector:"資訊服務",subSector:"電商",group:"獨立",rank:280,
   business:"PChome 電商集團"},
  {code:"6488",name:"環球晶",sector:"半導體",subSector:"矽晶圓",group:"中美晶集團",rank:38,business:"重複"},
  {code:"3293",name:"鈊象",sector:"資訊服務",subSector:"遊戲",group:"獨立",rank:99,business:"重複"},

  /* ========= 其他電子 ========= */
  {code:"3450",name:"聯鈞",sector:"其他電子",subSector:"光通訊",group:"獨立",rank:170,
   business:"光通訊主動元件、矽光子，CPO 概念股"},
  {code:"6533",name:"晶心科",sector:"其他電子",subSector:"處理器IP",group:"獨立",rank:140,
   business:"RISC-V 處理器矽智財領導廠"},
  {code:"6669",name:"緯穎",sector:"電腦及週邊",subSector:"雲端伺服器",group:"緯創集團",rank:22,business:"重複"},

  /* ========= 金融保險 ========= */
  {code:"2882",name:"國泰金",sector:"金融保險",subSector:"金控",group:"國泰集團",rank:5,
   business:"國泰人壽為核心的綜合金控，旗下含國泰世華銀、國泰證、國泰投信",
   products:["壽險","銀行","證券","資產管理"]},
  {code:"2881",name:"富邦金",sector:"金融保險",subSector:"金控",group:"富邦集團",rank:6,
   business:"富邦人壽 + 台北富邦銀行為核心，跨足台灣大、momo",
   products:["壽險","銀行","證券","電信(台灣大)"]},
  {code:"2891",name:"中信金",sector:"金融保險",subSector:"金控",group:"中信集團",rank:13,
   business:"中信銀為核心、台灣人壽、中信證",
   products:["銀行","壽險","證券"]},
  {code:"2885",name:"元大金",sector:"金融保險",subSector:"金控",group:"元大集團",rank:23,
   business:"元大證券、元大銀行、元大投信（台灣 ETF 龍頭）",
   products:["證券","銀行","ETF（0050）","投信"]},
  {code:"2884",name:"玉山金",sector:"金融保險",subSector:"金控",group:"獨立",rank:26,
   business:"以玉山銀行為核心，數位金融、財富管理"},
  {code:"2886",name:"兆豐金",sector:"金融保險",subSector:"金控",group:"獨立",rank:20,
   business:"兆豐國際商銀為核心，外匯與企業金融強"},
  {code:"2880",name:"華南金",sector:"金融保險",subSector:"金控",group:"獨立",rank:75,
   business:"華南銀行、華南永昌證"},
  {code:"2883",name:"開發金",sector:"金融保險",subSector:"金控",group:"中華開發集團",rank:39,
   business:"中華開發資本、凱基銀、凱基證、中國人壽"},
  {code:"2887",name:"台新金",sector:"金融保險",subSector:"金控",group:"台新集團",rank:55,
   business:"台新銀行為核心，與新光金合併進行中"},
  {code:"2890",name:"永豐金",sector:"金融保險",subSector:"金控",group:"何家集團",rank:80,
   business:"永豐銀行、永豐金證"},
  {code:"2888",name:"新光金",sector:"金融保險",subSector:"金控",group:"新光集團",rank:90,
   business:"新光人壽為核心，與台新金合併進行中"},
  {code:"2892",name:"第一金",sector:"金融保險",subSector:"金控",group:"獨立",rank:45,
   business:"第一商銀為核心，公股金控"},
  {code:"5876",name:"上海商銀",sector:"金融保險",subSector:"銀行",group:"獨立",rank:50,
   business:"高獲利、高股東權益報酬率的中型商銀"},
  {code:"5880",name:"合庫金",sector:"金融保險",subSector:"金控",group:"獨立",rank:67,
   business:"合作金庫銀行為核心，公股金控"},
  {code:"2823",name:"中壽",sector:"金融保險",subSector:"壽險",group:"中信集團",rank:120,
   business:"中信集團旗下壽險"},
  {code:"5871",name:"中租-KY",sector:"金融保險",subSector:"租賃",group:"中租集團",rank:31,
   business:"亞洲最大租賃集團，企業租賃、車輛租賃、太陽能融資",market:"KY"},
  {code:"2812",name:"台中銀",sector:"金融保險",subSector:"銀行",group:"獨立",rank:200},
  {code:"2834",name:"臺企銀",sector:"金融保險",subSector:"銀行",group:"獨立",rank:160},
  {code:"6005",name:"群益證",sector:"金融保險",subSector:"證券",group:"群益金鼎集團",rank:240},
  {code:"2867",name:"三商壽",sector:"金融保險",subSector:"壽險",group:"三商集團",rank:260},

  /* ========= 食品 ========= */
  {code:"1216",name:"統一",sector:"食品",subSector:"食品/飲料",group:"統一集團",rank:16,
   business:"台灣最大食品集團，含 7-11、星巴克、康是美、飲料、食品",
   products:["乳品/茶飲","泡麵","7-11(統一超)","星巴克台灣"],founded:1967},
  {code:"1227",name:"佳格",sector:"食品",subSector:"食品/油品",group:"獨立",rank:155,
   business:"桂格、福樂等品牌，乳品、麥片、油品",
   products:["桂格燕麥","福樂乳品","得意的一天油品"]},
  {code:"1229",name:"聯華",sector:"食品",subSector:"食品/麵粉",group:"聯華實業集團",rank:175,
   business:"麵粉、食品原料，集團含聯華電子、神通"},
  {code:"1231",name:"聯華食",sector:"食品",subSector:"零食",group:"聯華食品集團",rank:240,
   business:"可樂果、萬歲牌堅果等休閒食品"},
  {code:"1233",name:"天仁",sector:"食品",subSector:"茶葉",group:"獨立",rank:280,
   business:"茶葉零售、茶飲品牌"},
  {code:"1215",name:"卜蜂",sector:"食品",subSector:"肉品/飼料",group:"卜蜂集團",rank:170,
   business:"肉雞、飼料、加工肉品"},
  {code:"1210",name:"大成",sector:"食品",subSector:"飼料/肉品",group:"大成集團",rank:140,
   business:"飼料、肉雞、加工食品（含 BAR(漢堡)、佳佳食品)"},
  {code:"1232",name:"大統益",sector:"食品",subSector:"油品",group:"獨立",rank:185,
   business:"沙拉油、黃豆加工品"},
  {code:"1218",name:"泰山",sector:"食品",subSector:"食品/通路",group:"泰山集團",rank:280,
   business:"食用油、飲料、控股全家便利商店"},
  {code:"1234",name:"黑松",sector:"食品",subSector:"飲料",group:"獨立",rank:290,
   business:"沙士、汽水、瓶裝水"},
  {code:"2727",name:"王品",sector:"觀光餐旅",subSector:"餐飲",group:"王品集團",rank:240,
   business:"多品牌餐飲集團（王品、西堤、陶板屋等）"},
  {code:"2723",name:"美食-KY",sector:"觀光餐旅",subSector:"餐飲",group:"獨立",rank:200,
   business:"85度C 母公司，咖啡與烘焙連鎖",market:"KY"},
  {code:"2748",name:"雲品",sector:"觀光餐旅",subSector:"飯店",group:"雲朗集團",rank:295,
   business:"雲品溫泉酒店等多品牌飯店"},
  {code:"2729",name:"瓦城",sector:"觀光餐旅",subSector:"餐飲",group:"獨立",rank:300,
   business:"瓦城泰式、十食、非常泰等東南亞料理連鎖"},

  /* ========= 塑膠 ========= */
  {code:"1301",name:"台塑",sector:"塑膠",subSector:"石化",group:"台塑集團",rank:15,
   business:"台塑集團旗艦，PVC、PP、ABS、SM 主要生產者",
   products:["PVC","PP","ABS","SM"],founded:1954},
  {code:"1303",name:"南亞",sector:"塑膠",subSector:"石化/電子材料",group:"台塑集團",rank:17,
   business:"PVC 加工、聚酯、電子材料（玻纖布、PCB 銅箔基板）",
   products:["聚酯","電子材料","CCL","聚胺酯"]},
  {code:"1326",name:"台化",sector:"塑膠",subSector:"石化",group:"台塑集團",rank:27,
   business:"台塑集團石化原料，芳香烴、紡織纖維原料",
   products:["PX/PTA","PP/SAP","紡織纖維"]},
  {code:"1304",name:"台聚",sector:"塑膠",subSector:"石化",group:"台聚集團",rank:240},
  {code:"1305",name:"華夏",sector:"塑膠",subSector:"石化",group:"獨立",rank:260},
  {code:"1308",name:"亞聚",sector:"塑膠",subSector:"石化",group:"台聚集團",rank:280},
  {code:"1314",name:"中石化",sector:"塑膠",subSector:"石化",group:"威京集團",rank:175},
  {code:"6505",name:"台塑化",sector:"油電燃氣",subSector:"煉油",group:"台塑集團",rank:12,
   business:"台塑集團煉油與石化上游，台灣第二大煉油廠",
   products:["汽柴油","乙烯/丙烯","芳香烴"]},

  /* ========= 紡織纖維 ========= */
  {code:"1402",name:"遠東新",sector:"紡織纖維",subSector:"紡織/聚酯",group:"遠東集團",rank:88,
   business:"聚酯、PET 樹脂、紡織纖維，遠東集團母體",
   products:["PET","聚酯纖維","紡織"]},
  {code:"1409",name:"新纖",sector:"紡織纖維",subSector:"紡織",group:"新光集團",rank:200},
  {code:"1434",name:"福懋",sector:"紡織纖維",subSector:"紡織/輪胎簾布",group:"台塑集團",rank:155,
   business:"輪胎簾布、紡織、機能布料"},
  {code:"1440",name:"南紡",sector:"紡織纖維",subSector:"紡織",group:"統一集團",rank:280,
   business:"傳統紡織與不動產開發"},
  {code:"1455",name:"集盛",sector:"紡織纖維",subSector:"紡織",group:"獨立",rank:300},
  {code:"1476",name:"儒鴻",sector:"紡織纖維",subSector:"機能性服飾",group:"獨立",rank:69,
   business:"全球機能性服飾代工龍頭，Lululemon、Nike 主要供應",
   products:["機能性面料","運動服飾代工"]},
  {code:"1477",name:"聚陽",sector:"紡織纖維",subSector:"成衣",group:"獨立",rank:115,
   business:"專業成衣代工廠，Uniqlo、GAP、Target 客戶"},

  /* ========= 水泥 ========= */
  {code:"1101",name:"台泥",sector:"水泥",subSector:"水泥/能源",group:"台泥集團",rank:50,
   business:"水泥龍頭，跨足儲能、電池、和平電廠",
   products:["水泥","綠能","能源儲存","三元電池"]},
  {code:"1102",name:"亞泥",sector:"水泥",subSector:"水泥",group:"遠東集團",rank:85,
   business:"亞洲水泥，遠東集團旗下"},
  {code:"1103",name:"嘉泥",sector:"水泥",subSector:"水泥",group:"獨立",rank:280},
  {code:"1104",name:"環泥",sector:"水泥",subSector:"水泥",group:"獨立",rank:290},
  {code:"1108",name:"幸福",sector:"水泥",subSector:"水泥",group:"獨立",rank:300},

  /* ========= 鋼鐵 ========= */
  {code:"2002",name:"中鋼",sector:"鋼鐵",subSector:"一貫作業鋼廠",group:"中鋼集團",rank:28,
   business:"台灣最大鋼鐵集團，含中鋼、中鋼構、中鴻等",
   products:["熱軋","冷軋","鍍面","電磁鋼"],founded:1971},
  {code:"2014",name:"中鴻",sector:"鋼鐵",subSector:"鋼鐵加工",group:"中鋼集團",rank:230},
  {code:"2027",name:"大成鋼",sector:"鋼鐵",subSector:"不鏽鋼",group:"獨立",rank:140},
  {code:"2031",name:"新光鋼",sector:"鋼鐵",subSector:"鋼鐵加工",group:"獨立",rank:200},
  {code:"2015",name:"豐興",sector:"鋼鐵",subSector:"鋼筋/型鋼",group:"獨立",rank:175},
  {code:"2025",name:"千興",sector:"鋼鐵",subSector:"不鏽鋼",group:"獨立",rank:280},
  {code:"2023",name:"燁輝",sector:"鋼鐵",subSector:"鍍面鋼",group:"燁聯集團",rank:280},

  /* ========= 航運 ========= */
  {code:"2603",name:"長榮",sector:"航運",subSector:"貨櫃航運",group:"長榮集團",rank:10,
   business:"全球前七大貨櫃航商",
   products:["貨櫃航運","港口物流"]},
  {code:"2609",name:"陽明",sector:"航運",subSector:"貨櫃航運",group:"獨立",rank:44,
   business:"台灣公股大型貨櫃航運公司"},
  {code:"2615",name:"萬海",sector:"航運",subSector:"貨櫃航運",group:"獨立",rank:55,
   business:"亞洲區間航線龍頭"},
  {code:"2618",name:"長榮航",sector:"航運",subSector:"航空客運",group:"長榮集團",rank:52,
   business:"長榮集團航空"},
  {code:"2610",name:"華航",sector:"航運",subSector:"航空客運",group:"獨立",rank:75,
   business:"中華航空，國籍航空之一"},
  {code:"2606",name:"裕民",sector:"航運",subSector:"散裝航運",group:"遠東集團",rank:185},
  {code:"2637",name:"慧洋-KY",sector:"航運",subSector:"散裝航運",group:"獨立",rank:230,market:"KY"},

  /* ========= 汽車 ========= */
  {code:"2207",name:"和泰車",sector:"汽車",subSector:"汽車經銷",group:"和泰集團",rank:24,
   business:"Toyota / Lexus / Hino 在台總代理，租賃、二手車",
   products:["Toyota/Lexus 經銷","和運租車","和潤"]},
  {code:"2204",name:"中華",sector:"汽車",subSector:"汽車製造",group:"裕隆集團",rank:140,
   business:"商用車製造，三菱在台總代理"},
  {code:"2201",name:"裕隆",sector:"汽車",subSector:"汽車製造",group:"裕隆集團",rank:120,
   business:"納智捷、日產台灣製造，鴻海合作 MIH"},
  {code:"2227",name:"裕日車",sector:"汽車",subSector:"汽車製造",group:"裕隆集團",rank:155},
  {code:"2206",name:"三陽工業",sector:"汽車",subSector:"機車",group:"獨立",rank:135,
   business:"SYM 機車品牌"},
  {code:"1319",name:"東陽",sector:"汽車",subSector:"汽車零組件",group:"獨立",rank:185,
   business:"全球最大車燈/保險桿 AM 零組件廠"},
  {code:"1536",name:"和大",sector:"汽車",subSector:"汽車零組件",group:"獨立",rank:235,
   business:"電動車齒輪、變速箱齒輪"},
  {code:"1525",name:"江申",sector:"汽車",subSector:"汽車零組件",group:"獨立",rank:280},
  {code:"6605",name:"帝寶",sector:"汽車",subSector:"汽車零組件",group:"獨立",rank:170,
   business:"全球最大汽車車燈 AM 廠"},

  /* ========= 生技醫療 ========= */
  {code:"4174",name:"浩鼎",sector:"生技醫療",subSector:"新藥研發",group:"獨立",rank:215},
  {code:"4123",name:"晟德",sector:"生技醫療",subSector:"製藥",group:"晟德集團",rank:225},
  {code:"1789",name:"神隆",sector:"生技醫療",subSector:"原料藥",group:"統一集團",rank:280},
  {code:"4137",name:"麗豐-KY",sector:"生技醫療",subSector:"美容/連鎖",group:"獨立",rank:280,market:"KY"},
  {code:"4174",name:"浩鼎",sector:"生技醫療",subSector:"新藥",group:"獨立",rank:215,business:"重複"},
  {code:"4128",name:"中天",sector:"生技醫療",subSector:"製藥",group:"獨立",rank:300},
  {code:"4147",name:"中裕",sector:"生技醫療",subSector:"新藥",group:"獨立",rank:285},
  {code:"4736",name:"泰博",sector:"生技醫療",subSector:"醫材",group:"獨立",rank:290,
   business:"血糖機、體溫計、新冠快篩"},
  {code:"4126",name:"太醫",sector:"生技醫療",subSector:"醫材",group:"獨立",rank:300},
  {code:"6541",name:"泰福-KY",sector:"生技醫療",subSector:"生物相似藥",group:"獨立",rank:300,market:"KY"},
  {code:"1701",name:"中化",sector:"化學工業",subSector:"製藥/化工",group:"中化集團",rank:175},
  {code:"1707",name:"葡萄王",sector:"化學工業",subSector:"保健食品",group:"獨立",rank:225,
   business:"靈芝、樟芝等保健食品品牌"},

  /* ========= 化學工業 ========= */
  {code:"1717",name:"長興",sector:"化學工業",subSector:"特用化學",group:"長興集團",rank:200,
   business:"電子級化學品、UV 油墨"},
  {code:"1722",name:"台肥",sector:"化學工業",subSector:"肥料/化工",group:"獨立",rank:115,
   business:"化學肥料、深層海水、不動產（台肥土地）"},
  {code:"1723",name:"中碳",sector:"化學工業",subSector:"特用化學",group:"中鋼集團",rank:225,
   business:"煤化工，介相瀝青（鋰電池負極材料）"},
  {code:"4733",name:"上緯投控",sector:"化學工業",subSector:"風能/材料",group:"獨立",rank:240,
   business:"風電葉片樹脂，台灣離岸風電開發"},

  /* ========= 觀光餐旅 ========= */
  {code:"2731",name:"雄獅",sector:"觀光餐旅",subSector:"旅遊",group:"獨立",rank:185,
   business:"雄獅旅遊集團，跨足電商、餐飲、媒體"},
  {code:"2707",name:"晶華",sector:"觀光餐旅",subSector:"飯店",group:"晶華麗晶集團",rank:155,
   business:"晶華、麗晶、Just Sleep 飯店"},
  {code:"2722",name:"夏都",sector:"觀光餐旅",subSector:"飯店",group:"獨立",rank:300},
  {code:"9943",name:"好樂迪",sector:"觀光餐旅",subSector:"娛樂",group:"獨立",rank:295},

  /* ========= 貿易百貨 ========= */
  {code:"2912",name:"統一超",sector:"貿易百貨",subSector:"零售",group:"統一集團",rank:25,
   business:"7-11 台灣母公司，含黑貓宅急便、康是美、博客來、星巴克"},
  {code:"2915",name:"潤泰全",sector:"貿易百貨",subSector:"零售/紡織",group:"潤泰集團",rank:65,
   business:"控股潤泰新、南山人壽、紡織"},
  {code:"9904",name:"寶成",sector:"運動休閒",subSector:"製鞋",group:"寶成集團",rank:75,
   business:"全球最大運動鞋代工廠（Nike、adidas）"},
  {code:"9921",name:"巨大",sector:"運動休閒",subSector:"自行車",group:"巨大集團",rank:78,
   business:"GIANT 捷安特，全球自行車品牌龍頭"},
  {code:"2903",name:"遠百",sector:"貿易百貨",subSector:"百貨",group:"遠東集團",rank:140},
  {code:"2905",name:"三商",sector:"貿易百貨",subSector:"零售/餐飲",group:"三商集團",rank:280},

  /* ========= 油電燃氣 ========= */
  {code:"9914",name:"美利達",sector:"運動休閒",subSector:"自行車",group:"美利達集團",rank:155,
   business:"自行車製造，與 Specialized 合作"},
  {code:"9925",name:"新保",sector:"其他",subSector:"保全",group:"新光集團",rank:260},
  {code:"9926",name:"新海",sector:"油電燃氣",subSector:"瓦斯",group:"獨立",rank:300},

  /* ========= 建材營造 ========= */
  {code:"2542",name:"興富發",sector:"建材營造",subSector:"建設",group:"興富發集團",rank:140,
   business:"國內主力上市建商，住宅與商辦"},
  {code:"2545",name:"皇翔",sector:"建材營造",subSector:"建設",group:"獨立",rank:260},
  {code:"2548",name:"華固",sector:"建材營造",subSector:"建設",group:"獨立",rank:175},
  {code:"2520",name:"冠德",sector:"建材營造",subSector:"建設",group:"獨立",rank:250},
  {code:"5522",name:"遠雄",sector:"建材營造",subSector:"建設",group:"遠雄集團",rank:240},
  {code:"9933",name:"中鼎",sector:"建材營造",subSector:"統包工程",group:"中鼎集團",rank:120,
   business:"統包工程國際 EPC 龍頭，半導體廠/電廠工程"},

  /* ========= 電機機械 ========= */
  {code:"2049",name:"上銀",sector:"電機機械",subSector:"工具機/線性傳動",group:"上銀集團",rank:42,
   business:"全球第二大線性傳動產品（LM Guide、滾珠螺桿）製造商，工具機/半導體/醫療機器人",
   products:["線性滑軌","滾珠螺桿","工業機器人","醫療機器手臂"]},
  {code:"1503",name:"士電",sector:"電機機械",subSector:"重電/變壓器",group:"獨立",rank:140,
   business:"重電設備、變壓器、電力監控、AI 資料中心電力解決方案",
   products:["變壓器","配電盤","資料中心電力"]},
  {code:"1504",name:"東元",sector:"電機機械",subSector:"電機/家電",group:"東元集團",rank:155,
   business:"工業電機、家電（東元/SAMPO）、電動車馬達",
   products:["工業馬達","家電","電動車馬達"]},
  {code:"1513",name:"中興電",sector:"電機機械",subSector:"重電/工程",group:"獨立",rank:78,
   business:"GIS（氣體絕緣開關）、變壓器、AI 資料中心電力工程主要供應",
   products:["GIS","變壓器","太陽能電廠"]},
  {code:"1519",name:"華城",sector:"電機機械",subSector:"變壓器",group:"獨立",rank:65,
   business:"高壓變壓器，美國電網與 AI 資料中心訂單爆發",
   products:["高壓變壓器","風電變壓器"]},
  {code:"1514",name:"亞力",sector:"電機機械",subSector:"配電盤",group:"獨立",rank:230,
   business:"高低壓配電盤、智慧電網設備"},
  {code:"1597",name:"直得",sector:"電機機械",subSector:"線性傳動",group:"獨立",rank:225,
   business:"線性滑軌與精密元件"},
  {code:"1537",name:"廣隆",sector:"電機機械",subSector:"電池",group:"獨立",rank:240,
   business:"密閉式鉛酸電池，UPS/太陽能儲能"},

  /* ========= 更多 半導體 ========= */
  {code:"5234",name:"達興材料",sector:"半導體",subSector:"半導體材料",group:"達興集團",rank:180,
   business:"半導體製程化學品、面板光阻、CMP 漿料"},
  {code:"8016",name:"矽創",sector:"半導體",subSector:"IC設計",group:"獨立",rank:155,
   business:"中小尺寸 LCD Driver IC、TDDI、OLED Driver"},
  {code:"5471",name:"松翰",sector:"半導體",subSector:"IC設計",group:"獨立",rank:210,
   business:"消費性 SoC、物聯網晶片"},
  {code:"6789",name:"采鈺",sector:"半導體",subSector:"光學鍍膜/CIS",group:"台積電集團",rank:115,
   business:"CMOS 影像感測器後段製造，台積電轉投資"},
  {code:"6781",name:"AES-KY",sector:"半導體",subSector:"電池模組",group:"獨立",rank:140,market:"KY",
   business:"高效能電池模組（特斯拉 Cybertruck 供應）"},
  {code:"4763",name:"材料-KY",sector:"半導體",subSector:"半導體材料",group:"獨立",rank:160,market:"KY",
   business:"電子化學品、半導體研磨液"},
  {code:"6531",name:"愛普",sector:"半導體",subSector:"IC設計",group:"獨立",rank:200,
   business:"記憶體 IC 設計"},
  {code:"4960",name:"誠美材",sector:"半導體",subSector:"光學膜材料",group:"獨立",rank:280,
   business:"偏光板、光學膜"},
  {code:"6919",name:"世紀",sector:"半導體",subSector:"封測材料",group:"獨立",rank:290,
   business:"半導體用化學氣體"},
  {code:"3105",name:"穩懋",sector:"半導體",subSector:"化合物半導體",group:"獨立",rank:78,
   business:"重複"},
  {code:"6147",name:"頎邦",sector:"半導體",subSector:"封測",group:"獨立",rank:95,
   business:"Driver IC 封測領導廠，COF 卷帶式封裝"},
  {code:"2351",name:"順德",sector:"半導體",subSector:"封測導線架",group:"獨立",rank:175,
   business:"半導體封測導線架"},
  {code:"2369",name:"菱生",sector:"半導體",subSector:"封測",group:"獨立",rank:280,
   business:"傳統 IC 封測"},
  {code:"5285",name:"界霖",sector:"半導體",subSector:"封測",group:"獨立",rank:260,
   business:"IC 導線架"},

  /* ========= 更多 電腦及週邊 ========= */
  {code:"2316",name:"楠梓電",sector:"電子零組件",subSector:"PCB",group:"獨立",rank:140,
   business:"AI 伺服器與車用 PCB"},
  {code:"4915",name:"致伸",sector:"電腦及週邊",subSector:"電腦周邊",group:"獨立",rank:185,
   business:"鍵盤、滑鼠、影像產品 ODM"},
  {code:"3017",name:"奇鋐",sector:"電腦及週邊",subSector:"散熱",group:"獨立",rank:36,
   business:"重複"},
  {code:"3046",name:"建碁",sector:"電腦及週邊",subSector:"工業電腦",group:"獨立",rank:280},
  {code:"2455",name:"全新",sector:"半導體",subSector:"光通訊磊晶",group:"獨立",rank:175,
   business:"光通訊磊晶片，CPO 概念"},

  /* ========= 更多 電子零組件 ========= */
  {code:"6125",name:"廣運",sector:"電子零組件",subSector:"自動化/散熱",group:"獨立",rank:165,
   business:"自動化倉儲、半導體設備、散熱"},
  {code:"1582",name:"信錦",sector:"電子零組件",subSector:"機構件",group:"獨立",rank:200,
   business:"顯示器/電視支架"},
  {code:"6285",name:"啟碁",sector:"通信網路",subSector:"網通設備",group:"仁寶集團",rank:120,
   business:"重複"},
  {code:"6196",name:"帆宣",sector:"其他電子",subSector:"無塵室工程",group:"獨立",rank:175,
   business:"無塵室機電統包，半導體廠工程"},
  {code:"6442",name:"光聖",sector:"光電",subSector:"光通訊",group:"獨立",rank:225,
   business:"光通訊主動模組"},

  /* ========= 更多 金融保險 ========= */
  {code:"2845",name:"遠東銀",sector:"金融保險",subSector:"銀行",group:"遠東集團",rank:180},
  {code:"2812",name:"台中銀",sector:"金融保險",subSector:"銀行",group:"獨立",rank:200,business:"重複"},
  {code:"2849",name:"安泰銀",sector:"金融保險",subSector:"銀行",group:"獨立",rank:240},
  {code:"2820",name:"華票",sector:"金融保險",subSector:"票券",group:"獨立",rank:260},
  {code:"2855",name:"統一證",sector:"金融保險",subSector:"證券",group:"統一集團",rank:230},
  {code:"5878",name:"台名",sector:"金融保險",subSector:"保經",group:"獨立",rank:300},

  /* ========= 更多 紡織 / 食品 / 化工 ========= */
  {code:"1217",name:"愛之味",sector:"食品",subSector:"飲料",group:"獨立",rank:280},
  {code:"1235",name:"興泰",sector:"食品",subSector:"漁產加工",group:"獨立",rank:300},
  {code:"4426",name:"利勤實",sector:"化學工業",subSector:"特用化學",group:"獨立",rank:280},
  {code:"1452",name:"宏益",sector:"紡織纖維",subSector:"紡織",group:"獨立",rank:300},
  {code:"1326",name:"台化",sector:"塑膠",subSector:"石化",group:"台塑集團",rank:27,business:"重複"},
  {code:"4506",name:"崇友",sector:"電機機械",subSector:"電梯",group:"獨立",rank:230,
   business:"國產電梯品牌"},
  {code:"6235",name:"華孚",sector:"電子零組件",subSector:"鎂鋁合金",group:"獨立",rank:280,
   business:"NB/手機鎂合金機殼"},

  /* ========= 更多 生技 / 醫療 ========= */
  {code:"4131",name:"晶宇",sector:"生技醫療",subSector:"檢驗",group:"獨立",rank:300},
  {code:"4133",name:"亞諾法",sector:"生技醫療",subSector:"診斷試劑",group:"獨立",rank:300},
  {code:"1762",name:"中化生",sector:"生技醫療",subSector:"原料藥",group:"中化集團",rank:280},
  {code:"4119",name:"旭富",sector:"生技醫療",subSector:"原料藥",group:"獨立",rank:295},

  /* ========= 更多 綠能 / 太陽能 ========= */
  {code:"3576",name:"聯合再生",sector:"綠能環保",subSector:"太陽能",group:"獨立",rank:280,
   business:"太陽能電池與模組（茂迪、新日光、昱晶合併）"},
  {code:"6443",name:"元晶",sector:"綠能環保",subSector:"太陽能",group:"獨立",rank:230,
   business:"太陽能矽晶圓與電池"},
  {code:"3686",name:"達能",sector:"綠能環保",subSector:"太陽能",group:"獨立",rank:300},
  {code:"3014",name:"聯陽",sector:"半導體",subSector:"IC設計",group:"聯電集團",rank:170,business:"重複"},

  /* ========= 更多 油電燃氣 / 公用事業 ========= */
  {code:"9908",name:"大台北",sector:"油電燃氣",subSector:"瓦斯",group:"大台北瓦斯集團",rank:280},
  {code:"9931",name:"欣高",sector:"油電燃氣",subSector:"瓦斯",group:"獨立",rank:295},
  {code:"9939",name:"宏全",sector:"其他",subSector:"包材",group:"宏全集團",rank:230,
   business:"飲料瓶包材、PET 瓶、瓶蓋"},

  /* ========= 更多 觀光餐旅 ========= */
  {code:"2706",name:"第一店",sector:"觀光餐旅",subSector:"百貨",group:"獨立",rank:300},
  {code:"2762",name:"中租企業",sector:"金融保險",subSector:"租賃",group:"獨立",rank:300},
  {code:"5536",name:"聖暉",sector:"建材營造",subSector:"無塵室工程",group:"獨立",rank:155,
   business:"半導體廠機電統包"},
  {code:"3293",name:"鈊象",sector:"資訊服務",subSector:"遊戲",group:"獨立",rank:99,business:"重複"},

  /* ========= 運動休閒 ========= */
  {code:"1736",name:"喬山",sector:"運動休閒",subSector:"運動器材",group:"獨立",rank:230,
   business:"全球大型健身器材集團，跑步機、橢圓機"},

  /* ========= 玻璃陶瓷 ========= */
  {code:"1802",name:"台玻",sector:"玻璃陶瓷",subSector:"玻璃",group:"獨立",rank:200,
   business:"玻璃容器、平板玻璃"},
  {code:"1810",name:"和成",sector:"玻璃陶瓷",subSector:"衛浴陶瓷",group:"獨立",rank:280},

  /* ========= 造紙 ========= */
  {code:"1903",name:"士紙",sector:"造紙",subSector:"紙業",group:"獨立",rank:300},
  {code:"1905",name:"華紙",sector:"造紙",subSector:"紙業",group:"永豐餘集團",rank:230,
   business:"工業用紙、文化用紙"},
  {code:"1907",name:"永豐餘",sector:"造紙",subSector:"紙業/控股",group:"永豐餘集團",rank:175,
   business:"控股造紙、紙器、生技、能源"},
  {code:"1909",name:"榮成",sector:"造紙",subSector:"紙器",group:"獨立",rank:240},

  /* ========= 橡膠 ========= */
  {code:"2105",name:"正新",sector:"橡膠",subSector:"輪胎",group:"獨立",rank:75,
   business:"全球大型輪胎廠（瑪吉斯品牌）"},
  {code:"2106",name:"建大",sector:"橡膠",subSector:"輪胎",group:"獨立",rank:140,
   business:"自行車與機車輪胎"},
  {code:"2104",name:"中橡",sector:"橡膠",subSector:"碳煙",group:"獨立",rank:230,
   business:"碳煙（橡膠原料）"},
  {code:"2108",name:"南帝",sector:"橡膠",subSector:"合成橡膠",group:"獨立",rank:285,
   business:"NBR 合成橡膠（醫療手套主原料）"},

  /* ========= 更多 電器電纜 ========= */
  {code:"1605",name:"華新",sector:"電器電纜",subSector:"電線/不鏽鋼",group:"華新集團",rank:90,
   business:"電線電纜、不鏽鋼、半導體封裝（與恆耀合作）"},
  {code:"1604",name:"聲寶",sector:"電器電纜",subSector:"家電/不動產",group:"聲寶集團",rank:185},
  {code:"1609",name:"大亞",sector:"電器電纜",subSector:"電線電纜",group:"獨立",rank:155},

  /* ========= 更多 食品/餐飲 ========= */
  {code:"2748",name:"雲品",sector:"觀光餐旅",subSector:"飯店",group:"雲朗集團",rank:295,business:"重複"},
  {code:"2723",name:"美食-KY",sector:"觀光餐旅",subSector:"餐飲",group:"獨立",rank:200,business:"重複"},

  /* ========= 中華電 系統整合等 ========= */
  {code:"6285",name:"啟碁",sector:"通信網路",subSector:"網通設備",group:"仁寶集團",rank:120,business:"重複"},

  /* ========= 居家生活 / 其他 ========= */
  {code:"9910",name:"豐泰",sector:"運動休閒",subSector:"製鞋",group:"獨立",rank:130,
   business:"Nike 主要鞋類代工夥伴"},
  {code:"2204",name:"中華",sector:"汽車",subSector:"汽車製造",group:"裕隆集團",rank:140,business:"重複"},

  /* ========= 補充：其他重要中大型股 ========= */
  {code:"4438",name:"廣越",sector:"紡織纖維",subSector:"成衣",group:"獨立",rank:230,
   business:"羽絨衣代工龍頭，The North Face、UNIQLO 客戶"},
  {code:"3528",name:"安馳",sector:"電子通路",subSector:"半導體通路",group:"獨立",rank:280},
  {code:"3231",name:"緯創",sector:"電腦及週邊",subSector:"NB/伺服器",group:"緯創集團",rank:33,business:"重複"},
  {code:"8341",name:"日友",sector:"綠能環保",subSector:"環保處理",group:"獨立",rank:280,
   business:"事業廢棄物處理"},
  {code:"3051",name:"力特",sector:"光電",subSector:"偏光板",group:"獨立",rank:285,
   business:"偏光片、光學膜"},
  {code:"3653",name:"健策",sector:"半導體",subSector:"散熱基板",group:"獨立",rank:88,business:"重複"},
  {code:"2059",name:"川湖",sector:"電子零組件",subSector:"伺服器滑軌",group:"獨立",rank:95,business:"重複"},
  {code:"6691",name:"洋華",sector:"光電",subSector:"觸控面板",group:"獨立",rank:300},
  {code:"4994",name:"傳奇",sector:"資訊服務",subSector:"遊戲",group:"獨立",rank:290,
   business:"線上遊戲開發商"},
  {code:"3661",name:"世芯-KY",sector:"半導體",subSector:"IC設計服務",group:"獨立",rank:35,business:"重複"},
  {code:"6754",name:"匯僑設計",sector:"建材營造",subSector:"室內設計",group:"獨立",rank:300},
  {code:"3131",name:"弘塑",sector:"半導體",subSector:"半導體設備",group:"獨立",rank:230,
   business:"半導體濕製程設備"},
  {code:"3293",name:"鈊象",sector:"資訊服務",subSector:"遊戲",group:"獨立",rank:99,business:"重複"},
  {code:"2049",name:"上銀",sector:"電機機械",subSector:"工具機/線性傳動",group:"上銀集團",rank:42,business:"重複"},
  {code:"6679",name:"鈺太",sector:"半導體",subSector:"IC設計",group:"獨立",rank:230,
   business:"麥克風與音訊 IC"},
  {code:"6488",name:"環球晶",sector:"半導體",subSector:"矽晶圓",group:"中美晶集團",rank:38,business:"重複"},
  {code:"5269",name:"祥碩",sector:"半導體",subSector:"IC設計",group:"華碩集團",rank:80,business:"重複"},
  {code:"8454",name:"富邦媒",sector:"資訊服務",subSector:"電商",group:"富邦集團",rank:60,
   business:"momo 富邦媒，台灣最大綜合電商"},
  {code:"6890",name:"台新新光金",sector:"金融保險",subSector:"金控（合併中）",group:"台新集團",rank:70,
   business:"台新金與新光金合併新主體（2025/7 起）"},
  {code:"3017",name:"奇鋐",sector:"電腦及週邊",subSector:"散熱",group:"獨立",rank:36,business:"重複"},
  {code:"4763",name:"材料-KY",sector:"半導體",subSector:"半導體材料",group:"獨立",rank:160,market:"KY",business:"重複"},
  {code:"2412",name:"中華電",sector:"通信網路",subSector:"電信",group:"獨立",rank:8,business:"重複"},
  {code:"2603",name:"長榮",sector:"航運",subSector:"貨櫃航運",group:"長榮集團",rank:10,business:"重複"},
  {code:"3711",name:"日月光投控",sector:"半導體",subSector:"封裝測試",group:"日月光集團",rank:11,business:"重複"},
  {code:"2308",name:"台達電",sector:"電子零組件",subSector:"電源/工業電源",group:"台達集團",rank:7,business:"重複"},
  {code:"2891",name:"中信金",sector:"金融保險",subSector:"金控",group:"中信集團",rank:13,business:"重複"},
  {code:"2382",name:"廣達",sector:"電腦及週邊",subSector:"NB/伺服器",group:"獨立",rank:9,business:"重複"},

  /* ========= 補充：通信網路、其他電子 ========= */
  {code:"2419",name:"仲琦",sector:"通信網路",subSector:"網通",group:"仁寶集團",rank:280,
   business:"Cable Modem、寬頻終端設備"},
  {code:"3023",name:"信邦",sector:"電子零組件",subSector:"連接器/線材",group:"獨立",rank:160,business:"重複"},
  {code:"6443",name:"元晶",sector:"綠能環保",subSector:"太陽能",group:"獨立",rank:230,business:"重複"},
  {code:"6182",name:"合晶",sector:"半導體",subSector:"矽晶圓",group:"獨立",rank:200,
   business:"8 吋矽晶圓"},
  {code:"2354",name:"鴻準",sector:"電子零組件",subSector:"金屬機構件",group:"鴻海集團",rank:80,business:"重複"},
  {code:"8358",name:"金居",sector:"電子零組件",subSector:"銅箔",group:"獨立",rank:255,
   business:"電子級銅箔，AI 伺服器與 CCL 用"},
  {code:"6191",name:"精成科",sector:"電子零組件",subSector:"PCB",group:"獨立",rank:180,
   business:"PCB，伺服器與通訊應用"},
  {code:"2492",name:"華新科",sector:"電子零組件",subSector:"被動元件",group:"華新集團",rank:90,
   business:"MLCC、晶片電阻，國巨主要競爭者"},

  /* ========= ETF/指數 ========= */
  {code:"0050",name:"元大台灣50",sector:"ETF/指數",subSector:"市值型ETF",group:"元大投信",rank:0,
   business:"追蹤台灣 50 指數的 ETF，涵蓋台股市值最大的 50 家公司",
   products:["市值加權指數型 ETF"]},
  {code:"0056",name:"元大高股息",sector:"ETF/指數",subSector:"高股息ETF",group:"元大投信",rank:0,
   business:"追蹤台灣高股息指數，月配/季配息設計"},
  {code:"00762",name:"元大全球AI",sector:"ETF/指數",subSector:"主題ETF",group:"元大投信",rank:0,
   business:"追蹤全球 AI 主題的 ETF"},
  {code:"00878",name:"國泰永續高股息",sector:"ETF/指數",subSector:"高股息ETF",group:"國泰投信",rank:0,
   business:"ESG + 高股息策略，季配息"},
  {code:"00919",name:"群益台灣精選高息",sector:"ETF/指數",subSector:"高股息ETF",group:"群益投信",rank:0},
  {code:"00929",name:"復華台灣科技優息",sector:"ETF/指數",subSector:"高股息ETF",group:"復華投信",rank:0,
   business:"科技股 + 高息策略，月月配"},
  {code:"00940",name:"元大臺灣價值高息",sector:"ETF/指數",subSector:"高股息ETF",group:"元大投信",rank:0},
];

/* ============================================================
   連結關係資料：[from, to, type, label]
   type: supply (供應鏈) | industry (同產業) | group (集團) | correlation (歷史相關性)
   ============================================================ */
window.LINKS = [
  /* ========== 集團關係 ========== */
  // 鴻海集團
  ["2317","2354","group","鴻海控股鴻準"],
  ["2317","2392","group","鴻海控股正崴"],
  ["2317","6230","group","鴻海集團"],
  ["2317","3481","group","鴻海控股群創"],
  ["2317","4961","group","鴻海集團"],
  ["2317","3413","group","鴻海集團"],
  // 台塑集團
  ["1301","1303","group","台塑四寶"],
  ["1301","1326","group","台塑四寶"],
  ["1301","6505","group","台塑四寶"],
  ["1303","1326","group","台塑四寶"],
  ["1303","6505","group","台塑四寶"],
  ["1326","6505","group","台塑四寶"],
  ["1303","8046","group","南電為南亞子公司"],
  ["1301","1434","group","台塑集團福懋"],
  // 統一集團
  ["1216","2912","group","統一控股統一超"],
  ["1216","1789","group","統一集團"],
  ["1216","1440","group","統一集團"],
  // 遠東集團
  ["1402","1102","group","遠東集團"],
  ["1402","2606","group","遠東集團"],
  ["1402","2903","group","遠東集團"],
  ["1402","4904","group","遠東集團遠傳"],
  // 富邦集團
  ["2881","3045","group","富邦集團"],
  // 中信集團
  ["2891","2823","group","中信控股中壽"],
  // 台積電集團
  ["2330","5347","group","台積電轉投資"],
  ["2330","3443","group","台積電轉投資創意"],
  // 聯電集團
  ["2303","3034","group","聯電集團"],
  ["2303","3035","group","聯電集團"],
  ["2303","3037","group","聯電集團"],
  ["2303","3014","group","聯電集團"],
  // 緯創集團
  ["3231","6669","group","緯創控股緯穎"],
  // 華碩集團
  ["2357","4938","group","華碩前 spin-off 和碩"],
  ["2357","5269","group","華碩集團祥碩"],
  // 裕隆集團
  ["2201","2204","group","裕隆集團"],
  ["2201","2227","group","裕隆集團"],
  // 國巨集團
  // 中鋼集團
  ["2002","2014","group","中鋼控股中鴻"],
  ["2002","1723","group","中鋼集團中碳"],
  // 中華開發集團
  // 長榮集團
  ["2603","2618","group","長榮集團"],
  // 國泰集團 (含金融、世華)
  // 新光集團
  ["2888","1409","group","新光集團"],
  ["2888","9925","group","新光集團"],
  // 仁寶/啟碁
  // 元大集團
  ["2885","0050","group","元大投信發行"],
  ["2885","0056","group","元大投信發行"],
  ["2885","00762","group","元大投信發行"],
  ["2885","00940","group","元大投信發行"],
  // 國泰投信
  ["2882","00878","group","國泰投信發行"],

  /* ========== 供應鏈 ========== */
  // 半導體核心鏈：晶圓代工 -> IC設計
  ["2330","2454","supply","台積電代工聯發科"],
  ["2330","3034","supply","台積電代工聯詠"],
  ["2330","2379","supply","台積電代工瑞昱"],
  ["2330","3661","supply","台積電代工世芯"],
  ["2330","3443","supply","台積電代工創意"],
  ["2303","3034","supply","聯電代工聯詠"],
  // 晶圓 -> 封測
  ["2330","3711","supply","台積電→日月光封測"],
  ["2330","2449","supply","台積電→京元電測試"],
  ["3711","6271","supply","封測產業鏈"],
  // 晶圓 -> 矽晶圓 / 載板 / 設備
  ["6488","2330","supply","環球晶供應晶圓"],
  ["8046","2330","supply","南電 ABF 載板供應"],
  ["3037","2330","supply","欣興 ABF 載板供應"],
  ["3413","2330","supply","京鼎供應半導體設備"],
  ["3413","2454","supply","京鼎供應設備"],
  // AI 伺服器供應鏈
  ["2330","2454","supply","台積電/聯發科 AI 晶片"],
  ["2330","3661","supply","世芯 ASIC -> 台積電代工"],
  ["3661","2382","supply","廣達 AI 伺服器使用 ASIC"],
  ["2454","2382","supply","聯發科 ASIC -> 廣達"],
  ["2382","2317","supply","廣達/鴻海 AI server"],
  ["6669","2382","supply","緯穎/廣達同 ODM"],
  ["3017","2382","supply","奇鋐供應廣達散熱"],
  ["3017","6669","supply","奇鋐供應緯穎散熱"],
  ["3017","2317","supply","奇鋐供應鴻海散熱"],
  ["3653","2330","supply","健策散熱基板供應"],
  ["6230","2317","supply","超眾供應散熱"],
  ["8210","2382","supply","勤誠供應機殼"],
  ["8210","6669","supply","勤誠供應緯穎機殼"],
  ["2059","2382","supply","川湖滑軌供應"],
  ["2059","6669","supply","川湖滑軌"],
  // 被動元件
  ["2327","2317","supply","國巨 MLCC 供應鴻海"],
  ["2327","2454","supply","國巨供應 MLCC"],
  // 鴻海蘋果鏈
  ["2330","2317","supply","台積電 A 系列晶片→鴻海組裝"],
  ["3008","2317","supply","大立光鏡頭→鴻海組裝"],
  ["2354","2317","supply","鴻準機構件供應"],
  ["2474","2317","supply","可成機殼"],
  ["3406","2317","supply","玉晶光鏡頭"],
  // 面板供應鏈
  ["2409","2317","supply","友達面板供應"],
  ["3481","2317","supply","群創面板供應"],
  // 電源 / 台達電鏈
  ["2308","2382","supply","台達電供應伺服器電源"],
  ["2308","6669","supply","台達電供應緯穎"],
  ["2308","2317","supply","台達電供應 EV/工業電源"],
  ["2301","2382","supply","光寶供應電源"],
  // PCB / 載板鏈
  ["6213","8046","supply","聯茂 CCL → 南電載板"],
  ["6213","3037","supply","聯茂 CCL → 欣興"],
  ["3044","2382","supply","健鼎 PCB 供應"],
  // 中鋼 -> 下游汽車/造船
  ["2002","2603","supply","中鋼鋼板 -> 造船"],
  ["2002","2207","supply","中鋼汽車鋼板"],
  ["2002","2201","supply","中鋼汽車鋼板"],
  // 台塑石化 -> 塑膠
  ["6505","1301","supply","台塑化原料"],
  ["6505","1303","supply","台塑化原料"],
  ["6505","1326","supply","台塑化原料"],
  // 紡織鏈
  ["1402","1476","supply","遠東新聚酯供應"],
  ["1402","1477","supply","遠東新聚酯"],
  // 食品通路
  ["1216","2912","supply","統一供應 7-11"],
  ["1227","2912","supply","佳格供應 7-11"],
  // 零售與航空、運輸略
  ["2603","2317","supply","長榮海運→鴻海全球出貨"],
  ["2618","2317","supply","長榮航貨運"],
  // 電動車鏈
  ["2317","2308","supply","鴻海 MIH ↔ 台達電"],
  ["2317","2207","supply","鴻海 vs Toyota 商用車合作"],
  ["1101","2308","supply","台泥儲能 ↔ 台達電"],

  /* ========== 同產業（核心代表） ========== */
  // 半導體晶圓代工同業
  ["2330","2303","industry","晶圓代工"],
  ["2330","5347","industry","晶圓代工"],
  ["2330","6770","industry","晶圓代工"],
  ["2303","5347","industry","晶圓代工"],
  ["2303","6770","industry","晶圓代工"],
  // IC 設計同業
  ["2454","3034","industry","IC設計"],
  ["2454","2379","industry","IC設計"],
  ["3034","2379","industry","IC設計"],
  ["3034","5269","industry","IC設計"],
  ["2379","5269","industry","IC設計"],
  ["3034","8081","industry","IC設計"],
  ["3034","6202","industry","IC設計"],
  // 封測同業
  ["3711","2449","industry","封測產業"],
  ["3711","6271","industry","封測產業"],
  // 三大電信
  ["2412","3045","industry","電信業"],
  ["2412","4904","industry","電信業"],
  ["3045","4904","industry","電信業"],
  // NB/Server 代工
  ["2382","3231","industry","NB ODM"],
  ["2382","2356","industry","NB ODM"],
  ["3231","2356","industry","NB ODM"],
  ["2382","6669","industry","Server ODM"],
  ["3231","6669","industry","Server ODM"],
  // 主機板品牌
  ["2376","2377","industry","主機板/顯卡"],
  ["2357","2376","industry","主機板/品牌"],
  ["2357","2353","industry","NB 品牌"],
  // 三大金控
  ["2882","2881","industry","壽險金控"],
  ["2881","2891","industry","金控"],
  ["2882","2891","industry","金控"],
  ["2885","2884","industry","金控"],
  ["2884","2886","industry","金控"],
  ["2882","2888","industry","壽險金控"],
  // 貨櫃三雄
  ["2603","2609","industry","貨櫃航運"],
  ["2603","2615","industry","貨櫃航運"],
  ["2609","2615","industry","貨櫃航運"],
  // 雙航
  ["2618","2610","industry","國籍航空"],
  // 水泥兩強
  ["1101","1102","industry","水泥兩強"],
  // 石化大廠
  ["1301","1303","industry","台塑四寶"],
  // 鋼鐵大廠
  ["2002","2015","industry","鋼鐵業"],
  ["2002","2027","industry","鋼鐵業"],
  // 紡織機能
  ["1476","1477","industry","機能性紡織"],
  // 鏡頭兩強
  ["3008","3406","industry","光學鏡頭"],
  // 面板兩強
  ["2409","3481","industry","面板"],
  // 散熱
  ["3017","6230","industry","散熱模組"],
  ["3017","3653","industry","散熱"],
  // 通路雙雄
  ["3702","3036","industry","半導體通路"],
  // 金融租賃
  ["5871","2885","industry","非銀行金融"],
  // 自行車
  ["9921","9914","industry","自行車雙雄"],
  // 三大油氣
  ["6505","1101","industry","能源/原料"],
  // 建商
  ["2542","2548","industry","建設"],
  ["2542","2520","industry","建設"],
  ["2548","2545","industry","建設"],
  // 餐飲
  ["2727","2729","industry","餐飲"],
  ["2727","2723","industry","餐飲/食品"],
  // 不同產業之大型 cluster 連結
  ["1216","2912","industry","食品/通路"],

  /* ========== 歷史股價相關性（高度相關，常見配對） ========== */
  // 半導體三雄常一起波動
  ["2330","2454","correlation","AI/半導體領頭"],
  ["2330","3711","correlation","半導體生態"],
  // AI 伺服器族群
  ["2382","6669","correlation","AI server 族群"],
  ["3231","6669","correlation","AI server"],
  ["2382","2376","correlation","AI 伺服器供應"],
  ["3017","6669","correlation","AI 伺服器散熱"],
  // 貨櫃三雄
  ["2603","2609","correlation","運價連動"],
  ["2603","2615","correlation","運價連動"],
  // 金控雙雄
  ["2882","2881","correlation","金控雙雄"],
  // 鴻海集團聯動
  ["2317","2354","correlation","鴻海集團"],
  ["2317","6669","correlation","AI 概念聯動"],
  // 中租 vs 元大金 (非銀金融)
  ["5871","2885","correlation","非銀金融"],
  // 紡織機能
  ["1476","1477","correlation","機能性紡織"],
  // 自行車兩強
  ["9921","9914","correlation","自行車雙雄"],
  // 鋼鐵航運景氣循環
  ["2002","2603","correlation","景氣循環"],
  // 台塑四寶聯動
  ["1301","1303","correlation","石化聯動"],
  ["1301","1326","correlation","石化聯動"],
  ["1303","1326","correlation","石化聯動"],
];

/* 去除重複條目 */
(function dedupe(){
  const seen = new Set();
  window.COMPANIES = window.COMPANIES.filter(c => {
    if(seen.has(c.code) || c.business==="重複條目（已列），略過" || c.business==="重複") return false;
    seen.add(c.code);
    return true;
  });
})();
